version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: stockdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-server:
    build: .
    container_name: stock-api
    restart: always
    ports:
      - "8090:8000"  # Acceso directo para debug
    env_file:
      - .env
    depends_on:
      - db
    command: >
      bash -c "
      sleep 3 &&
      python create_tables.py &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  mqtt-worker:
    build: .
    container_name: mqtt-worker
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: >
      bash -c "
      sleep 5 &&
      python mqtt_worker/subscriber.py
      "

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api-server

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/certbot
      --email lucho123hrg@gmail.com
      --agree-tos
      --no-eff-email
      -d e0.finask.me"
      
volumes:
  postgres_data:
